# Generated by Django 3.0.6 on 2020-05-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizaçãodesseCorno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='what_i_need_to_do',
            table='what',
        ),
    ]
