# Generated by Django 3.0.6 on 2020-05-25 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizaçãodesseCorno', '0002_auto_20200518_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='etec_tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('dia_entrega', models.DateField(default=datetime.datetime)),
            ],
            options={
                'db_table': 'etec',
            },
        ),
    ]
