# Generated by Django 3.0.6 on 2020-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizaçãodesseCorno', '0004_auto_20200525_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.CharField(max_length=100)),
                ('descri', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nota',
            },
        ),
    ]
